### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by adicle** [laravel/airlock#11]
Might have missed something, but getting `CSRF token mismatch` after running a request to the API (after running the `airlock/csrf-cookie`, which seems to be returning everything fine)?

Added the monorepo here for help:
https://github.com/adicle/test-app

Just testing a really really simple SPA test with API but still having the issue.

**Comment by taylorotwell** [comment]
Can't recreate.

**Comment by adicle** [comment]
After installing a fresh instance of Laravel, using the documented way to using Laravels own auth and then following the README.md of this we are still getting `CSRF token mismatch`?

**Comment by DCzajkowski** [comment]
To every request after `/airlock/csrf-cookie` you need to add a `X-XSRF-TOKEN` header with the value of the `XSRF-TOKEN` cookie.

**Comment by lukesnowden** [comment]
I'm guessing, because `Auth::routes();` is in your `web.php` it is protected by the CSRF token middleware because in the service provider it states to use the `web` middleware group. 

I'm assuming you remove `Auth::routes();` from `web.php` and add it to `api.php` because in the service provider these routes are protected by the `api` middleware group which should have the new `EnsureFrontendRequestsAreStateful::class` middleware. You then post to `/api/login`.

**Comment by lukesnowden** [comment]
Remove `window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';` from `bootstrap.php`

**Comment by danpastori** [comment]
@DCzajkowski That makes complete sense. I was running into an issue doing a local NuxtJS install and I can't get access to the XSRF-TOKEN. By default NuxtJS runs on `localhost` domain and my API is in a development environment that's `api.app.test`. 

I kept getting a 419 for the CSRF token being invalidated. Is this due to the different top level domains? I have it working through Nuxt's Auth module with issuing an access token (https://github.com/laravel/airlock#issuing-api-tokens) but not with the SPA auth way (https://github.com/laravel/airlock#spa-authentication). 

Thank you for your help!

**Comment by adicle** [comment]
@danpastori I think this package using the CSRF token is built towards building your SPA into Laravel itself then just using Laravel as an API, which is where I was slightly confused. As you said it still works fine with using access tokens but needs CSRF disabling for the API requests.

**Comment by DCzajkowski** [comment]
@danpastori Is the NuxtJS app server rendered? Maybe you need to attach an Origin header for API calls made from the backend. Is this the thing you are having problems with?

**Comment by danpastori** [comment]
So here's my setup. 

## NuxtJS Install
I have a directory, let's call `/frontend` that is my NuxtJS install. In there, I have a basic SPA NuxtJS install (no server side rendering). I created a frontend `/login` route to log in the user by providing a form.

When fired up, this is a standard NuxtJS install on a dev machine with the URL of http://localhost:3000.

## Laravel Install
I have another directory, `/api` that is my Laravel install. In that directory, I have a bare bones Laravel install with just UI auth installed and Laravel Airlock and configured per the docs (middleware, and config setup with `localhost` as a stateless domain`.

## The Process
The user enters their email and password and I call the `login()` method which looks like this:
```
this.$axios.get('https://api/airlock/csrf-cookie').then(function( response ){
    this.$axios.post('https://api/login', {
        email: this.email,
        password: this.password
    });
}.bind(this));
```
I'm using the Nuxt Axios module and following: https://github.com/laravel/airlock#spa-authentication. Now here's where the issue comes in.

After I submit, the first request goes through just fine:
<img width="1012" alt="Screen Shot 2020-01-11 at 8 26 01 AM" src="https://user-images.githubusercontent.com/2365103/72207253-40f24700-344c-11ea-8efc-a44057e3e8cf.png">

However, when I make the subsequent POST request to the `/login` route I get a CSRF token mismatch 419 response:
<img width="1012" alt="Screen Shot 2020-01-11 at 8 28 52 AM" src="https://user-images.githubusercontent.com/2365103/72207265-7434d600-344c-11ea-9bfb-fc397220ea0c.png">

You can also see that the XSRF token is not being sent in the request headers and when I receive the initial response from the `/csrf-cookie` request the cookies aren't getting set.

## Solutions I've Tried
1. Added `{withCredentials: true}` to the axios request.
2. Sending request through Postman to see if it was something with a config in the default Nuxt Axios Module.

## What Worked
* When I fired up my old SPA *WITHIN* the laravel install so the host was the same top level domain. Worked like a charm.
* Issuing access tokens like: https://github.com/laravel/airlock#issuing-api-tokens. This is what I was doing with Passport and switching in Airlock, it still worked. 

## Questions
1. Is the CSRF token only valid IF the top level domains are the same? I understand that normally this is how it should work and kind of the point is to have the same top level domains. I was just confused with the `stateless` domains in the Airlock config file. This will be resolved on deployment to production.
2. If the CSRF token is supposed to match top level domains, I can work with my development environment and make that happen. However, is https://github.com/laravel/airlock#issuing-api-tokens a good option for scenarios where this might not be the case? 

Thank you all for your help, I really appreciate the time and effort. Airlock is a beautiful package and can't wait to work with it more!

**Comment by taylorotwell** [comment]
All sounds like incorrect CORS configuration.

**Comment by danpastori** [comment]
Hi @taylorotwell ,

That could easily be the case, thank you for looking into this! 

For CORS configuration and testing I've been using the Spatie/Cors package (https://github.com/spatie/laravel-cors). The only changes that I tweaked to their default profile was to `allow_credentials` and exposed and allowed the `Set-Cookie` headers.

For references my CORS config file is:
```
<?php

return [

    /*
     * A cors profile determines which origins, methods, headers are allowed for
     * a given requests. The `DefaultProfile` reads its configuration from this
     * config file.
     *
     * You can easily create your own cors profile.
     * More info: https://github.com/spatie/laravel-cors/#creating-your-own-cors-profile
     */
    'cors_profile' => Spatie\Cors\CorsProfile\DefaultProfile::class,

    /*
     * This configuration is used by `DefaultProfile`.
     */
    'default_profile' => [

        'allow_credentials' => true,

        'allow_origins' => [
            '*',
        ],

        'allow_methods' => [
            'POST',
            'GET',
            'OPTIONS',
            'PUT',
            'PATCH',
            'DELETE',
        ],

        'allow_headers' => [
            'Content-Type',
            'X-Auth-Token',
            'Origin',
            'Authorization',
            'Set-Cookie'
        ],

        'expose_headers' => [
            'Cache-Control',
            'Content-Language',
            'Content-Type',
            'Expires',
            'Last-Modified',
            'Pragma',
            'Set-Cookie'
        ],

        'forbidden_response' => [
            'message' => 'Forbidden (cors).',
            'status' => 403,
        ],

        /*
         * Preflight request will respond with value for the max age header.
         */
        'max_age' => 60 * 60 * 24,
    ],
];
```

When I call the initial `/airlock/csrf-cookie` , CORS works and the proper `set-cookie` header is returned, but I get a 419 on the POST request to `/login`.

**Comment by nmsmith22389** [comment]
As a side note to this topic I think it might be nice to have a guide or something in the README showing how to use this package in conjunction with the nuxt-auth package.

When I first started using Nuxt I was shocked that there isn’t a straight forward way to use Nuxt/nuxt-auth + Laravel/Passport. Before that, I had thought that was pretty much the point of using Passport.

**Comment by danpastori** [comment]
I’ll definitely do a PR when I figure it out. I have the local Nuxt Auth configured to call everything correctly, just probably messed up my CORS. I’m so stoked to use airlock with NUXT!

**Comment by jeitnier** [comment]
You might be missing `'X-Requested-With'` header in your CORS config.

**Comment by DCzajkowski** [comment]
Try this for debugging purposes:
```js
this.$axios.get('https://api/airlock/csrf-cookie').then(() => {
    this.$axios.post('https://api/login', {
        email: this.email,
        password: this.password,
    }, {
        headers: {
            'X-XSRF-TOKEN': (() => {
                const name = 'XSRF-TOKEN'
                const cookies = '; ' + document.cookie
                const parts = cookies.split('; ' + name + '=')
                const value = parts.length == 2 ? parts.pop().split(';').shift() : null

                console.log('>>> XSRF-TOKEN', value)

                return value
            })(),
        },
    })
})
```

This should set the `X-XSRF-TOKEN` header explicitly using the value of `XSRF-TOKEN` coockie and console.log this value. Check the contents of the console. If the cookie value is null, there is your problem. Probably CORS misconfiguration. If it worked, then it seems like Axios is not attaching the header for some reason.

**Comment by robertotcestari** [comment]
@danpastori I am having the same problem. It works perfectly with both (api and frontend) under localhost. But when I replace my api url to valet (airlock.test), i get the same errors.

I believe if API and Frontend are not in the same top domain, than we should use Airlock with access-token, but not with the stateful session. Am I correct?

**Comment by lukesnowden** [comment]
Change the url in config/airlock.php

**Comment by robertotcestari** [comment]
> Change the url in config/airlock.php

Hi @lukesnowden, thanks for the reply. Tried this, but with no success. I guess it is not possible to share session cookies to different domains. We can get the xsrf-token and session response cookie, but it is not sent back in the next api call.  that's the reason of the token mismatch and even disabling xsrf, the user is not logged in the next call.

**Comment by georgeboot** [comment]
Same issue here. The `GET /airlock/csrf-cookie` was made seconds before and the cookie set by it's response matches the cookie send to the login call.

<img width="982" alt="Schermafbeelding 2020-01-13 om 16 23 21" src="https://user-images.githubusercontent.com/884482/72267837-0988c380-3621-11ea-8832-e9ea00104034.png">

**Comment by danpastori** [comment]
Hi All, 

So I've been spending some time with the issue and I've gotten a little bit closer to solving it.

## Updated CORS Library
First, I updated my CORS library to be the BarryVDH (which is now fruitcake/laravel-cors). I did this because it was mentioned by Taylor that it will be integrated in Laravel 7.0 (https://twitter.com/taylorotwell/status/1216198072319037440?s=20) and I figured, the best way to test would be to use the package.

## Current CORS Config

The changes to the default config are as follows:
```
'paths' => [
    'airlock/csrf-cookie',
    'login',
    'api/*'
],
```
and
```
'allowed_origins' => ['http://localhost:3000'],
```
I explicitly set the `allowed_origins` to my local host and *NOT* the `*`. I read about this within the Axios GitHub (sorry I lost the link), but it mentioned that for any POST, we had to explicitly set the origin.

## Airlock Config
I also set the airlock config to explicitly be my Nuxt domain as well:
```
'stateful' => [
    'http://localhost:3000',
],
```

## Nuxt Login Call
Since I'm working within Nuxt, I wanted to limit the amount of variables and use their Auth package. The call I make for authentication is as follows:

```
this.$axios.get('https://API/airlock/csrf-cookie', {
    headers: {
        'X-Requested-With': 'XMLHttpRequest'
    },
    withCredentials: true
}).then(function( response ){
    this.$auth.loginWith('local', {
        data: {
            email: this.email,
            password: this.password
        },
        withCredentials: true,
        headers: {
            'X-Requested-With': 'XMLHttpRequest'
        },
    });
}.bind(this));
```
I ensure that the `withCredentials` is set to `true` so it passes the cookies correctly.

Now when I inspect my request, I see that under the cookies sent with the request, the XSRF-TOKEN is being sent along to the POST `/login` route. @robertotcestari I had the same issue where these weren't being sent, but the current config I have set up, sends the cookies.

<img width="941" alt="Screen Shot 2020-01-13 at 11 32 02 AM" src="https://user-images.githubusercontent.com/2365103/72285688-7b004c00-35f8-11ea-8672-077552cf8cd9.png">

This is great! However, I'm still getting a 419 response. 

## Current Questions
Diving into the VerifyCsrfToken.php middleware, it looks for the header `X-CSRF-TOKEN` or `X-XSRF-TOKEN`. Since these are not headers in my request (they are in the cookies), do I have to set up Axios to send as a header? If so, is there any instructions on how to send as a header vs a cookie?

Thanks a ton!

**Comment by taylorotwell** [comment]
It works fine for me:

CORS configuration for testing:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/463230/72349269-d20e2b80-36a1-11ea-93a0-c3ccad33d6cd.png">

Set axios `withCredentails` to true as a global default, not per request:

```js
axios.defaults.withCredentials = true;
```

My "stateful" config... you do not need "http", etc:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/463230/72349321-ee11cd00-36a1-11ea-9bf3-a84cf5db9489.png">

**Comment by georgeboot** [comment]
@taylorotwell I'm not too sure the issue has to do with CORS. When playing with in locally (using Insomnia or Postman) it also gives invalid csrf token, while both programs don't do anything with CORS. Please see my screenshot in earlier comment.

**Comment by taylorotwell** [comment]
@georgeboot did you try any of my instructions in the previous post?

**Comment by georgeboot** [comment]
@taylorotwell yes but no luck.
Even disabled the CORS package altogether, but that doesn't help either.

**Comment by danpastori** [comment]
@taylorotwell Thank you for all of the help, I was able to get it working in one scenario with Nuxt!

Here's what made the difference:

## CORS
A lot of this had to do with CORS, but also with the cookie domain. For CORS, the only change I made to the default `fruitcake/laravel-cors` package was to set `'supports_credentials' => true` and to add the Airlock routes to the cors file:
```
/*
     * You can enable CORS for 1 or multiple paths.
     * Example: ['api/*']
     */
    'paths' => [
        'airlock/csrf-cookie',
        'login',
        'api/*'
    ],
```

## Nuxt
By default NuxtJS runs on http://localhost:3000. According to a couple issues I read about, in order for a qualified domain, you need at least one `.` (https://stackoverflow.com/a/1188145). You also need your session domain set in `session.php` as @taylorotwell mentioned here: https://github.com/laravel/airlock/issues/11#issuecomment-574181474.

We have a testing infrastructure so I threw a Nuxt install under a subdomain and set that per suggestion () to be `.TLD.test`. This worked! We got an X-XSRF-TOKEN header passed and proper airlock authentication!

In my case, once I changed the TLD away from `localhost`, and adjusted the `session.php` it worked right away. Hope this helps someone!

**Comment by robmpreston** [comment]
@danpastori Similar issues here, but your solution didn't work sadly. Well, it did in a sense. The CSRF error went away and it successfully logs in. I can see the cookie being set and also sent with API calls, but I always get a 401 unauthorized on `/api/user`. Something weird going on but don't have time to mess with it further now.

**Comment by kono0514** [comment]
Additionally I had to set SESSION_DRIVER=cookie in .env file to make it work with API routes such as /api/user

**Comment by robmpreston** [comment]
> Additionally I had to set SESSION_DRIVER=cookie in .env file to make it work with API routes such as /api/user

Wonder if that's my issue. Will try later.

**Comment by danpastori** [comment]
So I finally got it 100% working. The `SESSION_DRIVER` = cookie is one of the missing links. The other was definitely getting NuxtJS and Laravel on subdomains of the same TLD.

Here is my code repo for the Laravel API with Airlock: https://github.com/serversideup/airlock-laravel-api

Here is my code repo for the NuxtJS install with the Nuxt Auth Module: https://github.com/serversideup/airlock-nuxt-frontend

If you guys have any questions, let me know and I can help trouble shoot

**Comment by robmpreston** [comment]
Awesome thanks - going to give it another go here in a bit.

**Comment by robmpreston** [comment]
It worked - thanks guys!

**Comment by vrerabek** [comment]
> Additionally I had to set SESSION_DRIVER=cookie in .env file to make it work with API routes such as /api/user

This helped me also with 'CSRF token mismatch'. (api + nuxt both on localhost)

**Comment by narrative1st** [comment]
My apologies ahead of time for adding this to a closed issue, but as this is auth + nuxt + laravel, I wanted to leave this here in case anyone else spends days trying to get it work...

I was able to solve my issues by using `credentials: true`, NOT `withCredentials` in the `axios` section of `nuxt.config.js`. Not sure why, and I actually moved over to Passport to get auth to finally work (I assume it's somewhat similar to Airlock).

I hope this helps someone!

(for ref: this post on [laravel/nuxt api](https://dev.to/stefant123/secure-authentication-in-nuxt-spa-with-laravel-as-back-end-19a9) is what finally worked for me)

**Comment by mansouralex** [comment]
Hi @danpastori , we are facing the same issue that the sent header name is "XSRF-TOKEN" and not "X-XSRF-TOKEN" what was your issue on this part specifically?

**Comment by danpastori** [comment]
@mansouralex So what worked for me was making sure CORS was setup properly and Airlock allowed the subdomain. Once I got the NuxtJS app running on my local test machine with the same Top Level Domain as my API, then Axios sent everything correctly. By default, axios sets the name of this header to `X-XSRF-TOKEN` so make sure you didn't change the default.

When I didn't have the api on a subdomain or trying to do different top level domains, Axios would pass everything in the Cookie header, which was really weird. 

Here's a few notes I went through:

### CORS
* Ensure the withCredentials is allowed on the server side and that Axios is sending over the header

### Session Driver
* Ensure this is set to cookie 

### Airlock
* If you have a subdomain, make sure this is added (i.e api.example.com)
* The middleware is added correctly EnsureFrontendRequestsAreStateful

Hopefully that helps!

**Comment by mansouralex** [comment]
@danpastori Thanks for the information. Everything clear except the part of "have a subdomain added to Airlock". 

We have the API on a subdomain and we also have the SPA on another subdomain. 

Where should we make sure the API subdomain added?

**Comment by danpastori** [comment]
So in the `config/airlock.php` file make sure that you have your frontend added like:

```
'stateful' => [
        'frontend_subdomain.tld.test',
 ],
```

That's how I have mine set up to get everything working.

Also, now thinking about it, ensure your session domain in `config/session.php` is structured like this: 
`domain' => '.tld.test'

hat will make a valid cookie session for your domain. Let me know if that helps!

**Comment by mansouralex** [comment]
@danpastori Thanks for the help. Our back-end configuration was correct, and the issue was from the front-end side as we use Angular which has it's own Http Client service and not using Axios. But once we sent the needed headers with the correct names it worked just fine!

**Comment by JGamboa** [comment]
im having some trouble with this, im using localhost:8000 and  vue on laravel as spa, but in the web routes its working ok the session, but on api routes isnt working, it said "unauthenticated"

**Comment by robmpreston** [comment]
@JGamboa As mentioned in this thread, you'll need to put your frontend on a domain. The way I have it setup for apps using Airlock is the backend is `api.tld.test` and the frontend is `app.tld.test` for example, then follow the instructions on here to set it up.

**Comment by JGamboa** [comment]
@robmpreston  already done that i put it on mydomain.test, i have no problem with the web routes, only with the api routes, if i send the request to the web routes i get the user on my /user , but when i try on /api/user, i get the unauthenticated

**Comment by Deprigo** [comment]
Hello I'm also receive a 419 error.

**Front-End**: http://localhost:4200

Angular, using the [proxy approach](https://medium.com/better-programming/setup-a-proxy-for-api-calls-for-your-angular-cli-app-6566c02a8c4d) with the proxy.conf.json

When first loading my spa login, I make a request to http://localhost:4200/airlock/csrf-cookie (which forwards the request to http://api.example/airlock/csrf-cookie) and I successfully receive the XSRF-TOKEN.

When trying to login, my request header includes the XSRF-TOKEN and I receive the 419 error.

What's strange is that I am making an HTTP request to http://localhost:4200/api/login (which forwards the request to http://api.example/api/login) and is not protected by auth:airlock, but still I receive a 419.

Could this be, because I am on the http://localhost:4200 and not on a subdomain of api.example?

Also on Angular I have an interceptor that attaches the X-Request-With and Content-Type request headers. I also include the withCredentials so that the cookies are sent on the request

**Back-End**: http://api.example

Environment Variables - changed SESSION_DRIVER to cookie as stated by @danpastori 

airlock.php - I configured where my spa will be making the stateful requests from (localhost:4200)

kernel.php - I configured Airlock's middleware, according to the docs

cors.php - I set the supports_credentials to true.

session.php - I set the domain as localhost:4200

Thanks in advance.

**Comment by ashgibson** [comment]
I just had a similar issue and had to add 'airlock/csrf-cookie' to the paths config option in cors.php.

**Comment by yob-yob** [comment]
I don't really know what's wrong but I'm having this issue on chrome only.. 
but on firefox Dev Edition.. everything works fine

**Comment by mansouralex** [comment]
@yob-yob If you updated Chrome recently that could be the reason, as this update included some changes to the way cookies are handled; you can read more here: https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html

In order to have CSRF and Airlock work again, you just need to make sure that: `session.same_site` is set to `null`

**Comment by iihres** [comment]
> Hello I'm also receive a 419 error.
> 
> **Front-End**: http://localhost:4200
> 
> Angular, using the [proxy approach](https://medium.com/better-programming/setup-a-proxy-for-api-calls-for-your-angular-cli-app-6566c02a8c4d) with the proxy.conf.json
> 
> When first loading my spa login, I make a request to http://localhost:4200/airlock/csrf-cookie (which forwards the request to http://api.example/airlock/csrf-cookie) and I successfully receive the XSRF-TOKEN.
> 
> When trying to login, my request header includes the XSRF-TOKEN and I receive the 419 error.
> 
> What's strange is that I am making an HTTP request to http://localhost:4200/api/login (which forwards the request to http://api.example/api/login) and is not protected by auth:airlock, but still I receive a 419.
> 
> Could this be, because I am on the http://localhost:4200 and not on a subdomain of api.example?
> 
> Also on Angular I have an interceptor that attaches the X-Request-With and Content-Type request headers. I also include the withCredentials so that the cookies are sent on the request
> 
> **Back-End**: http://api.example
> 
> Environment Variables - changed SESSION_DRIVER to cookie as stated by @danpastori
> 
> airlock.php - I configured where my spa will be making the stateful requests from (localhost:4200)
> 
> kernel.php - I configured Airlock's middleware, according to the docs
> 
> cors.php - I set the supports_credentials to true.
> 
> session.php - I set the domain as localhost:4200
> 
> Thanks in advance.

Try running both applications on localhost
Back-End: localhost:8000 
Front: localhost:8080

**Comment by Abylaikhan** [comment]
Frontend(Vue):
axios.defaults.baseURL = 'http://localhost:8000'; //'http://back.airlock.local';

Backend(.env)
SESSION_DOMAIN=localhost #SESSION_DOMAIN=.airlock.local
AIRLOCK_STATEFUL_DOMAINS=localhost:8080 #AIRLOCK_STATEFUL_DOMAINS=front.airlock.local

**Comment by AndrewSavetchuk** [comment]
> @yob-yob If you updated Chrome recently that could be the reason, as this update included some changes to the way cookies are handled; you can read more here: https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html
> 
> In order to have CSRF and Airlock work again, you just need to make sure that: `session.same_site` is set to `null`

Yeah, the problem occur only in Chrome, however `settings same_site` to `null` don't work for me  :(

**Comment by mansouralex** [comment]
@AndrewSavetchuk Can you post a screenshot from your Chrome console - cookies tab?

**Comment by AndrewSavetchuk** [comment]
@mansouralex I've just figured out the issue. You were right.
I edited `config/session.php` but it didn't help. 

The problem was with Airlock Middleware:
`vendor/laravel/airlock/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php`

<img width="688" alt="Screen Shot 2020-03-12 at 5 36 51 PM" src="https://user-images.githubusercontent.com/14139435/76539059-eb0c4080-6488-11ea-86b7-334c5bfb86e4.png">

When I changed the 45th line to `null` it did the trick.

This is a temporary workaround for Airlock, I made a pull request with the reference to your comment.

I couldn't even think that the error was due to a new update in Chrome. 
Thank you so much, Alex! 🙂

**Comment by papalardo** [comment]
After some days searching solution, its did works with me.

```js
import Cookies from 'js-cookie'
import axios from 'axios'

axios.defaults.withCredentials = true

axios.get('http://localhost:8000/airlock/csrf-cookie')
   .then(response => {
       Cookies.set("X-XSRF-TOKEN", Cookies.get("XSRF-TOKEN"))
       // Login...
       axios.post('http://localhost:8000/login', {
         email: 'admin@admin.com',
         password: '@admin123'
       }).then((data) => {
         console.log(data);
       })
    });
    
```

or

```php
<?php 
namespace App\Http\Middleware; 
use Closure; 

class TransformApiHeaders  { 

    public function handle($request, Closure $next) {

        $cookie_name = 'XSRF-TOKEN'; 
        $token_cookie = $request->cookie($cookie_name); 

        if ($token_cookie !== null) { 
            $request->headers->add(["X-$cookie_name" => $token_cookie]); 
        }

        return $next($request); 
    }
}
```

in Kernel.php

```php
protected $middleware = [
   TransformApiHeaders::class,
   // ...
];
```

**Comment by mkarnicki** [comment]
@mansouralex You may want to have a look at `EnsureFrontendRequestsAreStateful`. First thing it does in `handle` is call `configureSecureCookieSessions`, which updates the configuration with
```
'session.http_only' => true,
'session.same_site' => 'lax',
```
Notice this happens regardless of what you set your `session.same_site` to.

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
