### ISSUE TITLE
Integration with Laravel Spark

### ISSUE THREAD

**Issue by jhull** [laravel/airlock#68]
After weeks of struggling to get Passport to work with my SPA, I return to Laravel Airlock to find it "just works", so thank you for that 🤗

My question is in regards to integrating Airlock with Spark install. I did Airlock first, then did manual install of Spark which overwrote some things (and had issues with tables already created). I can go in and manually fix, but I wonder if it would be helpful to have official documentation as to how to get the two to work nicely together (as they're both part of Laravel).

**Comment by driesvints** [comment]
Since Spark doesn't uses Airlock out of the box we'll probably won't be providing documentation ourselves. If you manage to get them working together you're free of course to share a blog post or something similar.

If you need help using the library please try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
